jobs:
  - name: generate-manifest
    type: manifest
    steps:
      - GET: nginx-image
      - GET: myEcsParams
      - GET: myReplicas

  - name: deploy-service
    type: ecsDeploy
    steps:
      - GET: generate-manifest
      - GET: ecsCluster
      # - GET: anotherReplicas
      # - GET: moreParams
      - GET: kickstarter
      
  - name: deploy-service-too
    type: ecsDeploy
    steps:
      - GET: dcl-deploy-service-four
      - GET: ecsCluster
      - GET: yetMoreReplicas
      
  - name: dcl-deploy-service-four
    type: dclDeploy
    steps:
      - GET: another-manifest
      - GET: dclCluster
      - GET: anotherReplicas
      - GET: myEcsParams
      
  - name: dcl-deploy-service-for-real
    type: dclDeploy
    steps:
      - GET: deploy-service
      - GET: dclCluster
      - GET: anotherReplicas

  - name: another-manifest
    type: manifest
    steps:
      - GET: busybox-image
      - GET: myEcsParams
      
  # - name: multi-manifest
  #   type: manifest
  #   steps:
  #     - GET: busybox-image
  #     - GET: myEcsParams
  #     - GET: generate-manifest
      
  # - name: yet-another-manifest
  #   type: manifest
  #   steps:
  #     - GET: scratch-image
      # - GET: myEcsParams
