jobs:
  - name: generate-manifest
    type: manifest
    integration: stephDocker #workaround for bug requiring everything to have an integration
    steps:
      - GET: nginx-image
      - GET: myEcsParams
      - GET: myReplicas

  - name: deploy-service
    type: ecsDeploy
    integration: stephDocker #workaround for bug requiring everything to have an integration
    steps:
      - GET: generate-manifest
      - GET: ecsCluster
      - GET: anotherReplicas
      
  - name: deploy-service-too
    type: ecsDeploy
    integration: stephDocker #workaround for bug requiring everything to have an integration
    steps:
      - GET: deploy-service
      - GET: test-cluster
      # - GET: yetMoreReplicas
      
  # - name: DCL-deploy-service
  #   type: dclDeploy
  #   integration: stephDocker #workaround for bug requiring everything to have an integration
  #   steps:
  #     - GET another-manifest
  #     - GET dclCluster
  #     - GET myReplicas

  # - name: multi-manifest
  #   type: manifest
  #   integration: stephDocker #workaround for bug requiring everything to have an integration
  #   steps:
  #     - GET busybox-image
  #     - GET myEcsParams
  #     - GET generate-manifest

  # - name: another-manifest
  #   type: manifest
  #   integration: stephDocker #workaround for bug requiring everything to have an integration
  #   steps:
  #     - GET busybox-image
      # - GET myEcsParams
      
  # - name: yet-another-manifest
  #   type: manifest
  #   integration: stephDocker #workaround for bug requiring everything to have an integration
  #   steps:
  #     - GET scratch-image
      # - GET myEcsParams
