jobs:
  - name: generate-manifest
    type: manifest
    steps:
      - GET: nginx-image
      - GET: myEcsParams
      - GET: myReplicas
      - GET: ecsDockerOpts2

  - name: deploy-service
    type: ecsDeploy
    steps:
      - GET: generate-manifest
      - GET: ecsCluster
      # - GET: anotherReplicas
      # - GET: moreParams
      - GET: kickstarter
      - PUT: nginx-image
      
  - name: deploy-service-too
    type: ecsDeploy
    steps:
      - GET: deploy-service
      - GET: another-manifest
      - GET: ecsCluster
      - GET: anotherReplicas
      # - GET: someMoreParams
      # - GET: myOverrideOpts2
      
  - name: dcl-deploy-service-four
    type: dclDeploy
    steps:
      - GET: another-manifest
      - GET: dclCluster
      - GET: yetMoreReplicas
      - GET: myEcsParams
      
  # - name: dcl-deploy-service-for-real
  #   type: dclDeploy
  #   steps:
  #     - GET: deploy-service
  #     - GET: dclCluster
      # - GET: anotherReplicas

  - name: another-manifest
    type: manifest
    steps:
      - GET: busybox-image
      - GET: myEcsParams
      - GET: yetMoreReplicas
      
  # - name: multi-manifest
  #   type: manifest
  #   steps:
  #     - GET: busybox-image
  #     - GET: myEcsParams
  #     - GET: generate-manifest
      
  # - name: yet-another-manifest
  #   type: manifest
  #   steps:
  #     - GET: scratch-image
      # - GET: myEcsParams
      
  - name: run-sample_python
    type: runCI
    steps:
      - GET: sample_python
      - PUT: nginx-image
