jobs:
  - name: generate-manifest
    type: manifest
    integration: stephDocker #workaround for bug requiring everything to have an integration
    steps:
      - GET nginx-image

  - name: deploy-service
    type: ecsDeploy
    integration: stephDocker #workaround for bug requiring everything to have an integration
    steps:
      - GET generate-manifest
      - GET ecsCluster

  - name: multi-manifest
    type: manifest
    integration: stephDocker #workaround for bug requiring everything to have an integration
    steps:
      - GET busybox-image
      - GET myEcsParams
      - GET generate-manifest
