jobs:
  - name: generate-manifest
    type: manifest
    integration: stephDocker #workaround for bug requiring everything to have an integration
    steps:
      - GET nginx-image
      - GET busybox-image
      - GET myEcsParams

  - name: deploy-service
    type: ecsDeploy
    integration: stephDocker #workaround for bug requiring everything to have an integration
    steps:
      - GET generate-manifest
      - GET ecsCluster
