jobs:
 # - name: generate-mongo-image-manifest-3
#    type: manifest
 #   steps:
 #     - GET: mongo-image
  #    - GET: myEcsParams

  - name: generate-mongo-image-manifest-6
    type: manifest
    steps:
      - GET: mongo-image
#      - GET: myReplicas
#      - GET: deploy-service

 # - name: deploy-service
#    type: ecsDeploy
#    steps:
#      - GET: generate-mongo-image-manifest-3
#      - GET: myEcsCluster

  - name: deploy-service-7
    type: dclDeploy
    steps:
      - GET: generate-mongo-image-manifest-6
      - GET: myDclCluster
    #  - GET: myEcsParams
 #     - GET: myOtherEcsParams
 
  - name: deploy-service-8
    type: ecsDeploy
    steps:
    #  - GET: generate-mongo-image-manifest-6
      - GET: myEcsCluster
      - GET: myReplicas
      - GET: deploy-service-7
      - GET: myEcsParams
 #     - GET: myOtherEcsParams
 
  - name: deploy-service-10
    type: ecsDeploy
    steps:
      - GET: generate-mongo-image-manifest-6
      - GET: myEcsCluster
  #    - GET: myReplicas
  #    - GET: deploy-service-7
  #    - GET: myEcsParams
 #     - GET: myOtherEcsParams
