jobs:
  - name: manifest1
    type: manifest
    steps:
      - IN: nginx-image
      - IN: triggerManifest1
      - IN: params1
      - TASK: managed

  - name: ecsDeployOrg
    type: deploy
    steps:
      - IN: manifest1
      - IN: ecsCluster
      # - IN: params2
      #   applyTo:
      #     - manifest1
      - TASK: managed
        deployMethod: upgrade
