triggers:
  - name: triggerb1
    type: trigger
    pointer:
      counter: 9
      
  - name: triggerb8
    type: trigger
    pointer:
      counter: 9
      
  - name: triggerGKE
    type: trigger
    pointer:
      counter: 39
  
  - name: triggerECS
    type: trigger
    pointer:
      counter: 12
  
  - name: triggerRelease1
    type: trigger
    pointer:
      counter: 5
  
  - name: triggerSamplePythonCI
    type: trigger
    pointer:
      counter: 7
