triggers:
  - name: trigger1
    type: trigger
    pointer:
      counter: 6
      
  - name: trigger2
    type: trigger
    pointer:
      counter: 3
      
  - name: triggerGKE
    type: trigger
    pointer:
      counter: 5
  
  - name: triggerECS
    type: trigger
    pointer:
      counter: 6

  - name: triggerECS2
    type: trigger
    pointer:
      counter: 4
  
  - name: triggerRelease1
    type: trigger
    pointer:
      counter: 1
  
  - name: triggerSamplePythonCI
    type: trigger
    pointer:
      counter: 1
      
  - name: triggerTripub
    type: trigger
    pointer:
      counter: 1
