jobs:
  - name: b-manifest1
    type: manifest
    steps:
      - GET: nginx-image
      - GET: triggerb1
      # - GET: doesntExist
      # - GET: replicas1
      # - GET: dockerOptions1

  - name: b-manifest8
    type: manifest
    steps:
      # - GET: params2
      # - GET: b-manifest1
      # - GET: replicas2
      - GET: busybox-image
      - GET: triggerb8

  - name: b-manifest9
    type: manifest
    steps:
      # - GET: params2
      - GET: replicas3

  - name: c-manifest8
    type: manifest
    steps:
      - GET: nginx-image

  # - name: samplePythonJob
  #   type: runCI
  #   steps:
  #     - GET: samplePython
  #     - GET: triggerSamplePythonCI


  - name: gke-cluster
    type: gkeDeploy
    # options:
    #   deployMethod: blueGreen
    steps:
      - GET: gkeCluster
      - GET: b-manifest1
      - GET: b-manifest8
      - GET: dockerOptions1
        applyTo: 
          - nginx-image
      - GET: dockerOptions2
        applyTo: 
          - b-manifest8
      - GET: dockerOptions3
      - GET: triggerGKE
      - GET: params1

  - name: ecs-service1
    type: ecsDeploy
    # options:
    #   deployMethod: upgrade
    steps:
      - GET: b-manifest1
      - GET: b-manifest8
      # - GET: release1
      - GET: ecsCluster
      - GET: triggerECS
      - GET: replicas2
        applyTo: 
          - b-manifest1
      #     - my-manifest2
      - GET: params1
        applyTo:
          - nginx-image
      - GET: dockerOptions2
      #   applyTo:
      #     - not-an-image
      # - GET: kickstarter
      # - PUT: nginx-image
      
  # - name: ecs-service2
  #   type: ecsDeploy
  #   steps:
  #     - GET: ecs-service1
  #     - GET: my-manifest2
  #     - GET: ecsCluster
  #     - GET: replicas3
      # - GET: params3
      # - GET: dockerOptions3
      
  # - name: dcl-service1
  #   type: dclDeploy
  #   steps:
  #     - GET: manifest2
  #     - GET: dclCluster
      
  # - name: dcl-service2
  #   type: dclDeploy
  #   steps:
  #     - GET: dcl-service1
  #     - GET: dclCluster
      
  # - name: run-sample_python
  #   type: runCI
  #   steps:
  #     - GET: sample_python
  #     - PUT: nginx-image
  
  - name: release1
    type: release
    options:
      action: patch
    steps:
      - GET: version3
      - GET: b-manifest1
      - GET: triggerRelease1

  # - name: release3
  #   type: release
  #   options:
  #     action: minor
  #   steps:
  #     - GET: version3

  - name: sh-sample-python
    type: runSh
    steps:
      GET: samplePython
      TASK:
        - script: ls
