jobs:
  - name: b-manifest1
    type: manifest
    steps:
      - GET: nginx-image
      - GET: triggerb1
      # - GET: doesntExist
      # - GET: replicas1
      # - GET: dockerOptions1
      - TASK: managed

  - name: b-manifest8
    type: manifest
    steps:
      # - GET: params2
      # - GET: b-manifest1
      # - GET: replicas2
      - GET: busybox-image
      - GET: triggerb8
      - TASK: managed      

  - name: b-manifest9
    type: manifest
    steps:
      # - GET: params2
      - GET: replicas3
      - TASK: managed

  - name: c-manifest8
    type: manifest
    steps:
      - GET: nginx-image
      - TASK: managed

  # - name: samplePythonJob
  #   type: runCI
  #   steps:
  #     - GET: samplePython
  #     - GET: triggerSamplePythonCI


  - name: gkeDeploy
    type: gkeDeploy
    steps:
      - GET: gkeCluster
      - GET: b-manifest1
      - GET: b-manifest8
      # - GET: params1
      #   applyTo: 
      #     - nginx-image
      # - GET: params2
      #   applyTo: 
      #     - b-manifest8
      # - GET: params3
      - GET: triggerGKE
      - GET: dockerOptions1
      - TASK: managed
        deployMethod: upgrade

  - name: ecsDeploy
    type: ecsDeploy
    steps:
      - GET: b-manifest1
      # - GET: b-manifest8
      # - GET: release1
      - GET: ecsCluster
      - GET: triggerECS
      - GET: replicas2
      #   applyTo: 
      #     - b-manifest1
      #     - my-manifest2
      # - GET: params1
      #   applyTo:
      #     - nginx-image
      # - GET: dockerOptions2
      #   applyTo:
      #     - not-an-image
      # - GET: kickstarter
      # - PUT: nginx-image
      - TASK: managed
        deployMethod: upgrade
  
  - name: tripubDeploy
    type: tripubDeploy
    steps:
      - GET: b-manifest8
      - GET: ecsCluster
      - GET: triggerTripub
      - TASK: managed
      
  # - name: ecs-service2
  #   type: ecsDeploy
  #   steps:
  #     - GET: ecs-service1
  #     - GET: my-manifest2
  #     - GET: ecsCluster
  #     - GET: replicas3
      # - GET: params3
      # - GET: dockerOptions3
      # - TASK: managed
      
  # - name: dcl-service1
  #   type: dclDeploy
  #   steps:
  #     - GET: manifest2
  #     - GET: dclCluster
  #     - TASK: managed
      
  # - name: dcl-service2
  #   type: dclDeploy
  #   steps:
  #     - GET: dcl-service1
  #     - GET: dclCluster
  #     - TASK: managed
      
  # - name: run-sample_python
  #   type: runCI
  #   steps:
  #     - GET: samplePython
  #     # - PUT: nginx-image
  #     - GET: triggerSamplePythonCI
  #     - TASK: managed
  
  - name: release1
    type: release
    steps:
      - GET: version3
      - GET: b-manifest1
      - GET: triggerRelease1
      - TASK: managed
        # bump: major

  # - name: release3
  #   type: release
  #   options:
  #     action: minor
  #   steps:
  #     - GET: version3
  #     - TASK: managed

  # - name: sh-sample-python
  #   type: runSh
  #   steps:
  #     GET: samplePython
  #     TASK: managed
  #       script: ls
