jobs:

  - name: runCLIJob
    type: runCLI
    steps:
      - IN: awsConfig
      - IN: awsIntegration
      - TASK:
        - script: "pwd"
        - script: "ls"
#        - script: mkdir -p ~/.aws
        - script: AWS_PATH=~/.aws        
#        - script: rm -f $AWS_PATH/config
#        - script: rm -f $AWS_PATH/credentials
#        - script: echo "[default]" >> $AWS_PATH/config
#        - script: echo "region=us-east-1" >> $AWS_PATH/config     
#       - script: echo "output=json" >> $AWS_PATH/config 
 #       - script: echo "here's the config file:"
 #       - script: cat $AWS_PATH/config
  #      - script: echo "[default]" >> $AWS_PATH/credentials
#        - script: echo "aws_access_key_id=$AWSINTEGRATION_INTEGRATION_AWS_ACCESS_KEY_ID" >> $AWS_PATH/credentials
#        - script: echo "aws_secret_access_key=$AWSINTEGRATION_INTEGRATION_AWS_SECRET_ACCESS_KEY" >> $AWS_PATH/credentials
#        - script: echo "here's the credentials file:"
#        - script: cat $AWS_PATH/credentials
        - script: aws configure set aws_access_key_id $AWSINTEGRATION_INTEGRATION_AWS_ACCESS_KEY_ID
        - script: aws configure set aws_secret_access_key $AWSINTEGRATION_INTEGRATION_AWS_SECRET_ACCESS_KEY
        - script: aws configure set region us-east-1
        - script: cat $AWS_PATH/credentials
        - script: cat $AWS_PATH/config
        - script: eb init "my-application-name" -r "us-east-1" -p "Node.js"
        - script: eb terminate --all --force "my-application-name"
        - script: aws ecs list-container-instances --cluster ECSCluster

# ==================== manifests
  - name: manifest1
    type: manifest
    steps:
      - IN: nginx-image
      - IN: params1
      - IN: replicas0      
      - TASK: managed
#     on_start:
#       - NOTIFY: slackNotification
#     on_success:
#       - NOTIFY: slackNotification
#     on_failure:
#       - NOTIFY: slackNotification


  - name: manifest2
    type: manifest
    steps:
      - IN: busybox-image
      - IN: params1
      - IN: replicas2      
      - TASK: managed      

  - name: manifest3
    type: manifest
    steps:
#      - IN: params1
#      - IN: replicas0
      - IN: scratch-image
      - TASK: managed      
      
#  - name: manifestIntoManifest
#    type: manifest
#    steps:
#      - IN: manifest1
#      - IN: manifest2
#      - IN: replicas2
#     - TASK: managed      
   
#  - name: manifestQuayPrivate
#    type: manifest
#    steps:
#      - IN: sample-node-quay-private
#      - TASK: managed  

#  - name: manifestGcrPrivate
#    type: manifest
#    steps:
#      - IN: busybox-gcr-private-image
#      - TASK: managed


# ==================== deploys
#  - name: gkeDeploy
#    type: deploy
#    steps:
#      - IN: manifest1
#      - IN: gkeCluster
#        deployMethod: upgrade

  - name: ecsDeploy
    type: deploy
    steps:
      - IN: manifest1
      - IN: manifest2
#      - IN: manifest3
      - IN: ecsCluster
      - TASK: managed
        deployMethod: upgrade      
        
#  - name: tripubDeploy
#    type: deploy
#    steps:
#      - IN: manifest1
#      - IN: tritonCluster
#      - TASK: managed
#        deployMethod: replace
      
#  - name: dclDeploy
#    type: deploy
#    steps:
#      - IN: manifest1
#      - IN: dclCluster
#      - TASK: managed
#        deployMethod: upgrade

#  - name: ddcDeploy
#    type: deploy
#    steps:
#      - IN: manifest1
#      - IN: replicas0
#      - IN: ddcCluster
#      - TASK: managed
#        deployMethod: upgrade

#  - name: ecsDeployWithLB
#    type: deploy
#    steps:
#      - IN: manifest2
#      - IN: stephLB
#        applyTo:
#         - manifest: manifest4
#           image: scratch-image
#           port: 3001
#      - IN: ecsCluster
#      - TASK: managed
#        deployMethod: upgrade   


# ==================== provisions
  - name: gkeProvisionService
    type: provision
    steps:
      - IN: params1
      - IN: gkeProvisionLoadBalancer
      - IN: gkeProvisionLoadBalancerToo
      - TASK: managed


# ==================== release
  - name: release1
    type: release
    steps:
#      - IN: ecsDeploy
      - IN: version1
      - IN: manifest3
      - IN: triggerRelease1
      - TASK: managed
      #   bump: major


# ==================== runSh
  - name: runSh
    type: runSh
    steps:
      - IN: nginx-image
      - IN: params1
      - IN: fakeGKEIntegration
      - IN: samplePython
      - IN: awsIntegration
      - TASK:
        - script: "pwd"
        - script: "ls"
        - script: sudo apt-get install tree
        - script: tree
        - script: cat $SAMPLEPYTHON_PATH/gitRepo/shippable.yml
        - script: mkdir -p ~/.aws
        - script: AWS_PATH=~/.aws        
        - script: rm -f $AWS_PATH/config
        - script: rm -f $AWS_PATH/credentials
        - script: echo "[default]" >> $AWS_PATH/config
        - script: echo "region=us-east-1" >> $AWS_PATH/config     
        - script: echo "output=json" >> $AWS_PATH/config 
        - script: echo "here's the config file:"
        - script: cat $AWS_PATH/config
        - script: echo "[default]" >> $AWS_PATH/credentials
        - script: echo "aws_access_key_id=$AWSINTEGRATION_INTEGRATION_AWS_ACCESS_KEY_ID" >> $AWS_PATH/credentials
        - script: echo "aws_secret_access_key=$AWSINTEGRATION_INTEGRATION_AWS_SECRET_ACCESS_KEY" >> $AWS_PATH/credentials
        - script: echo "here's the credentials file:"
        - script: cat $AWS_PATH/credentials
        - script: aws ecs list-container-instances --cluster ECSCluster
      # - OUT: nginx-image

  # - name: sh-sample-python
  #   type: runSh
  #   steps:
  #     IN: samplePython
  #     TASK: managed
  #       script: ls
  
