triggers:
  - name: trigger1
    type: trigger
    source:
      counter: 8
      
  - name: trigger2
    type: trigger
    source:
      counter: 8
      
  - name: triggerGKE
    type: trigger
    source:
      counter: 22
  
  - name: triggerECS
    type: trigger
    source:
      counter: 8
  
  - name: triggerRelease1
    type: trigger
    source:
      counter: 3
  
  - name: triggerSamplePythonCI
    type: trigger
    source:
      counter: 7
