triggers:
  - name: triggerb1
    type: trigger
    pointer:
      counter: 9
      
  - name: triggerb8
    type: trigger
    pointer:
      counter: 9
      
  - name: triggerGKE
    type: trigger
    pointer:
      counter: 58
  
  - name: triggerECS
    type: trigger
    pointer:
      counter: 28
  
  - name: triggerRelease1
    type: trigger
    pointer:
      counter: 7
  
  - name: triggerSamplePythonCI
    type: trigger
    pointer:
      counter: 7
      
  - name: triggerTripub
    type: trigger
    pointer:
      counter: 10
