jobs:
  - name: manifest1
    type: manifest
    steps:
      - IN: manifest2
      - IN: triggerManifest1
#      - IN: params1
      - TASK: managed
#     on_start:
#       - NOTIFY: slackNotification
#     on_success:
#       - NOTIFY: slackNotification
#     on_failure:
#       - NOTIFY: slackNotification

  - name: manifest2
    type: manifest
    steps:
      - IN: busybox-image
      - IN: triggerManifest2
      - TASK: managed      

  - name: manifest3
    type: manifest
    steps:
      - IN: nginx-image
#      - IN: params1
      - TASK: managed      
      
  - name: manifest4
    type: manifest
    steps:
      - IN: scratch-image
      - IN: replicas2
      - TASK: managed      

  - name: manifest5
    type: manifest
    steps:
      - IN: sample_node
      - IN: sample_node_gitlab
      - IN: scratch-image
      - IN: replicas2
      - TASK: managed      

#  - name: manifestQuayPrivate
#    type: manifest
#    steps:
#      - IN: sample-node-quay-private
#      - TASK: managed  

  - name: manifestGcrPrivate
    type: manifest
    steps:
      - IN: busybox-gcr-private-image
      - TASK: managed

  - name: gkeProvisionService
    type: provision
    steps:
      - IN: gkeService
      - TASK: managed

  - name: gkeDeploy
    type: deploy
    steps:
      - IN: gkeProvisionService
      - IN: gkeCluster
#      - IN: manifest4
#      - IN: replicas2
#      - IN: triggerGKE
      - TASK: managed
        deployMethod: upgrade

  - name: ecsDeploy
    type: deploy
    steps:
#      - IN: manifest4
      - IN: manifest4
      - IN: dockerOptions1
#      - IN: replicas1
      - IN: stephLB
        applyTo:
         - manifest: manifest4
           image: scratch-image
           port: 3001
      - IN: ecsCluster
      - TASK: managed
        deployMethod: upgrade      
        
#  - name: tripubDeploy
#    type: deploy
#    steps:
#      - IN: manifest4
#      - IN: tritonCluster
#      - IN: triggerTripub
#      - TASK: managed
#        deployMethod: replace
      
  # - name: dclService
  #   type: deploy
  #   steps:
  #     - IN: manifest2
  #     - IN: dclCluster
  #     - TASK: managed
  #       deployMethod: upgrade

  - name: release1
    type: release
    steps:
#      - IN: ecsDeploy
      - IN: version1
      - IN: release2
      - IN: manifest5
      - IN: triggerRelease1
      - TASK: managed
      #   bump: major

  - name: outrunsh
    type: runSh
    steps:
      - IN: gkeProvisionService
      - TASK:
        - script: "pwd"
        - script: "ls" 
    #    - script: "printenv"
    #    - script: echo "============================"
     #   - script: echo $STEPHNODECLUSTER_INTEGRATION_PRIVATEKEY
      # - OUT: nginx-image
      # - OUT: busybox-image

  # - name: sh-sample-python
  #   type: runSh
  #   steps:
  #     IN: samplePython
  #     TASK: managed
  #       script: ls
  
