jobs:
  - name: manifest1
    type: manifest
    steps:
      - IN: manifest2
      - IN: triggerManifest1
      - IN: params1
      - TASK: managed
    # on_start:
    #   - NOTIFY: slackNotification
    # on_success:
    #   - NOTIFY: slackNotification
    # on_failure:
    #   - NOTIFY: slackNotification

  - name: manifest2
    type: manifest
    steps:
      - IN: busybox-image
      - IN: triggerManifest2
      - TASK: managed      

  - name: manifest3
    type: manifest
    steps:
      - IN: nginx-image
      - IN: params1
      - TASK: managed      
      
  - name: manifest4
    type: manifest
    steps:
      - IN: scratch-image
      - IN: replicas2
      - TASK: managed      

  - name: manifest5
    type: manifest
    steps:
      - IN: scratch-image
      - IN: replicas2
      - TASK: managed      

  # - name: samplePythonJob
  #   type: runCI
  #   steps:
  #     - IN: samplePython
  #     - IN: triggerSamplePythonCI

  - name: gkeDeploy
    type: deploy
    steps:
      - IN: gkeCluster
      - IN: manifest3
      - IN: triggerGKE
      - TASK: managed
        deployMethod: replace     

  - name: ecsDeploy
    type: deploy
    steps:
      - IN: manifest1
      - IN: ecsCluster
      - IN: deployInput
      - TASK: managed
        deployMethod: upgrade      
  
  - name: deployInput
    type: deploy
    steps:
      - IN: manifest3
      - IN: replicas1
      - IN: ecsCluster
      - TASK: managed
        deployMethod: upgrade
        
  # - name: tripubDeploy
  #   type: deploy
  #   steps:
  #     - IN: manifest2
  #     - IN: tritonCluster
  #     - IN: triggerTripub
  #     - TASK: managed
  #       deployMethod: upgrade
      
  # - name: dclService
  #   type: deploy
  #   steps:
  #     - IN: manifest2
  #     - IN: dclCluster
  #     - TASK: managed
  #       deployMethod: upgrade
      
  # - name: dcl-service2
  #   type: dclDeploy
  #   steps:
  #     - IN: dcl-service1
  #     - IN: dclCluster
  #     - TASK: managed
      
  # - name: run-sample_python
  #   type: runCI
  #   steps:
  #     - IN: samplePython
  #     - IN: triggerSamplePythonCI
  #     - TASK: managed
  #     - OUT: busybox-image
  
  - name: release1
    type: release
    steps:
      - IN: ecsDeploy
      - IN: version1
      - IN: release2
      - IN: manifest5
      - IN: triggerRelease1
      - TASK: managed
      #   bump: major

  - name: release2
    type: release
    steps:
      - IN: version2
      - IN: manifest4
      - IN: triggerRelease2
      - TASK: managed

  # - name: release3
  #   type: release
  #   steps:
  #     - IN: version3
  #     - TASK: managed

  - name: outrunsh
    type: runSh
    steps:
      # - IN: busybox-image
      - IN: nginx-image
      - TASK:
        - script: "mkdir -p /build/state/" 
        - script: "touch /build/state/nginx-image.env" 
        - script: "echo 'versionName=2' >>  /build/state/nginx-image.env" 
        - script: "cat /build/state/nginx-image.env"
      # - OUT: nginx-image
      # - OUT: busybox-image

  # - name: sh-sample-python
  #   type: runSh
  #   steps:
  #     IN: samplePython
  #     TASK: managed
  #       script: ls
