jobs:

# ==================== manifests
  - name: manifest1
    type: manifest
    steps:
      - IN: nginx-image
      - TASK: managed
#     on_start:
#       - NOTIFY: slackNotification
#     on_success:
#       - NOTIFY: slackNotification
#     on_failure:
#       - NOTIFY: slackNotification

  - name: manifest2
    type: manifest
    steps:
      - IN: busybox-image
      - TASK: managed      

  - name: manifest3
    type: manifest
    steps:
      - IN: scratch-image
      - TASK: managed      
      
#  - name: manifestIntoManifest
#    type: manifest
#    steps:
#      - IN: manifest1
#      - IN: manifest2
#      - IN: replicas2
#     - TASK: managed      
   
#  - name: manifestQuayPrivate
#    type: manifest
#    steps:
#      - IN: sample-node-quay-private
#      - TASK: managed  

#  - name: manifestGcrPrivate
#    type: manifest
#    steps:
#      - IN: busybox-gcr-private-image
#      - TASK: managed


# ==================== deploys
#  - name: gkeDeploy
#    type: deploy
#    steps:
#      - IN: manifest1
#      - IN: gkeCluster
#        deployMethod: upgrade

#  - name: ecsDeploy
#    type: deploy
#    steps:
#      - IN: manifest1
#      - IN: replicas0
#      - IN: ecsCluster
#      - TASK: managed
#       deployMethod: upgrade      
        
#  - name: tripubDeploy
#    type: deploy
#    steps:
#      - IN: manifest1
#      - IN: tritonCluster
#      - TASK: managed
#        deployMethod: replace
      
  - name: dclService
    type: deploy
    steps:
      - IN: manifest1
      - IN: dclCluster
      - TASK: managed
        deployMethod: upgrade

#  - name: ecsDeployWithLB
#    type: deploy
#    steps:
#      - IN: manifest2
#      - IN: stephLB
#        applyTo:
#         - manifest: manifest4
#           image: scratch-image
#           port: 3001
#      - IN: ecsCluster
#      - TASK: managed
#        deployMethod: upgrade   


# ==================== provisions
  - name: gkeProvisionService
    type: provision
    steps:
      - IN: gkeService
      - TASK: managed


# ==================== release
  - name: release1
    type: release
    steps:
#      - IN: ecsDeploy
      - IN: version1
      - IN: manifest3
      - IN: triggerRelease1
      - TASK: managed
      #   bump: major


# ==================== runSh
  - name: runSh
    type: runSh
    steps:
      - IN: gkeProvisionService
      - TASK:
        - script: "pwd"
        - script: "ls" 
      # - OUT: nginx-image

  # - name: sh-sample-python
  #   type: runSh
  #   steps:
  #     IN: samplePython
  #     TASK: managed
  #       script: ls
  
