triggers:
  - name: triggerb1
    type: trigger
    pointer:
      counter: 9
      
  - name: triggerb8
    type: trigger
    pointer:
      counter: 9
      
  - name: triggerGKE
    type: trigger
    pointer:
      counter: 57
  
  - name: triggerECS
    type: trigger
    pointer:
      counter: 27
  
  - name: triggerRelease1
    type: trigger
    pointer:
      counter: 6
  
  - name: triggerSamplePythonCI
    type: trigger
    pointer:
      counter: 7
      
  - name: triggerTripub
    type: trigger
    pointer:
      counter: 9
