jobs:
  - name: manifest1
    type: manifest
    steps:
      - IN: nginx-image
      # - IN: outrunsh
        # versionNumber: 1202
      # - IN: triggerManifest1
      - IN: params1
      # - IN: newManifest1
      - TASK: managed
      # - IN: dockerOptions1
    # on_start:
    #   - NOTIFY: slackNotification
    # on_success:
    #   - NOTIFY: slackNotification
    # on_failure:
    #   - NOTIFY: slackNotification

  # - name: newManifest1
  #   type: manifest
  #   steps:
  #     - IN: scratch-image

  - name: manifest2
    type: manifest
    steps:
      # - IN: params2
      # - IN: manifest1
      # - IN: replicas2
      # - IN: scratch-image
      - IN: busybox-image
      - IN: triggerManifest2
      - TASK: managed      

  - name: manifest3
    type: manifest
    steps:
      - IN: busybox-image
      - TASK: managed   

  # - name: manifestIntoManifest
  #   type: manifest
  #   steps:
  #     - IN: manifest1

  # - name: samplePythonJob
  #   type: runCI
  #   steps:
  #     - IN: samplePython
  #     - IN: triggerSamplePythonCI

  - name: gkeDeploy2
    type: deploy
    steps:
      - IN: gkeCluster
      - IN: manifest2
      - IN: manifest1
      - IN: dockerOptions1
      - IN: params1
      # - IN: replicas1
      - IN: triggerGKE
      - TASK: managed
  #       deployMethod: upgrade     
      # - IN: manifest2
      # - IN: params1
      #   applyTo: 
      #     - nginx-image
      # - IN: params2
      #   applyTo: 
      #     - manifest2
      # - IN: params3

      # - IN: replicas4
      # - IN: badDockerOptions

  # - name: ecsDeploy
  #   type: deploy
  #   steps:
      # - IN: manifest2
      # - IN: ecsCluster
      # - IN: deployInput
      # - IN: release1
      # - TASK: managed
      #   deployMethod: upgrade      
      # - IN: manifest2

      # - IN: stephLB
      # - IN: triggerECS
      # - IN: params2
      #   applyTo: 
      #     - manifest1
      #     - manifest2
      # - IN: params1
      #   applyTo:
      #     - nginx-image
      # - IN: dockerOptions2
      # - OUT: nginx-image
      # - IN: badDockerOptions
      # - IN: dockerOptions1
    # on_success:
    #   - NOTIFY: slackNotification
    # on_failure:
    #   - NOTIFY: slackNotification
  
  - name: deployInput
    type: deploy
    steps:
      - IN: manifest1
      - IN: ecsCluster
      - TASK: managed
        deployMethod: upgrade
        
  # - name: tripubDeploy
  #   type: deploy
  #   steps:
  #     - IN: manifest2
  #     - IN: tritonCluster
  #     - IN: triggerTripub
  #     - TASK: managed
  #       deployMethod: upgrade
      
  # - name: dclService
  #   type: deploy
  #   steps:
  #     - IN: manifest2
  #     - IN: dclCluster
  #     - TASK: managed
  #       deployMethod: upgrade
      
  # - name: dcl-service2
  #   type: dclDeploy
  #   steps:
  #     - IN: dcl-service1
  #     - IN: dclCluster
  #     - TASK: managed
      
  - name: run-sample_python
    type: runCI
    steps:
      - IN: samplePython
      - IN: triggerSamplePythonCI
      - TASK: managed
      - OUT: busybox-image
  
  - name: release1
    type: release
    steps:
      # - IN: release2
      - IN: version1
      - IN: manifest3
      - IN: triggerRelease1
      - TASK: managed
        bump: major

  - name: release2
    type: release
    steps:
      - IN: version2
      - IN: release1
      - IN: deployInput
      - IN: manifest2
      - IN: triggerRelease2
      - TASK: managed

  # - name: release3
  #   type: release
  #   steps:
  #     - IN: version3
  #     - TASK: managed

  - name: outrunsh
    type: runSh
    steps:
      - IN: busybox-image
      - TASK:
        - script: "mkdir -p /build/state/" 
        - script: "touch /build/state/nginx-image.env" 
        - script: "echo 'versionName=2' >>  /build/state/nginx-image.env" 
        - script: "cat /build/state/nginx-image.env"
      - OUT: nginx-image

  # - name: sh-sample-python
  #   type: runSh
  #   steps:
  #     IN: samplePython
  #     TASK: managed
  #       script: ls
