jobs:
  - name: manifest1
    type: manifest
    steps:
      - IN: nginx-image
      - IN: triggerManifest1
      - TASK: managed
      # - IN: replicas1
      # - IN: dockerOptions1
    on_success:
      - NOTIFY: slackNotification
    on_failure:
      - NOTIFY: slackNotification


  # - name: manifest2
  #   type: manifest
  #   steps:
      # - IN: params2
      # - IN: manifest1
      # - IN: replicas2
      # - IN: busybox-image
      # - IN: triggerManifest2
      # - TASK: managed      

  # - name: samplePythonJob
  #   type: runCI
  #   steps:
  #     - IN: samplePython
  #     - IN: triggerSamplePythonCI

  # - name: gkeDeploy2
  #   type: deploy
  #   steps:
  #     - IN: gkeCluster
  #     - IN: manifest2
      # - IN: manifest2
      # - IN: params1
      #   applyTo: 
      #     - nginx-image
      # - IN: params2
      #   applyTo: 
      #     - manifest2
      # - IN: params3
      # - IN: triggerGKE2
      # - IN: replicas4
      # - IN: badDockerOptions
      # - TASK: managed
      #   deployMethod: upgrade        

  # - name: ecsDeploy
  #   type: deploy
  #   steps:
  #     - IN: manifest1
      # - IN: manifest2
      # - IN: release1
      # - IN: ecsCluster
      # - IN: triggerECS
      # - IN: replicas2
      #   applyTo: 
      #     - manifest1
      #     - manifest2
      # - IN: params1
      #   applyTo:
      #     - nginx-image
      # - IN: dockerOptions2
      # - OUT: nginx-image
      # - TASK: managed
      #   deployMethod: upgrade
  
  # - name: tripubDeploy
  #   type: tripubDeploy
  #   steps:
  #     - IN: manifest2
  #     - IN: ecsCluster
  #     - IN: triggerTripub
  #     - TASK: managed
      
  # - name: dcl-service1
  #   type: deploy
  #   steps:
  #     - IN: manifest2
  #     - IN: dclCluster
  #     - TASK: managed
      
  # - name: dcl-service2
  #   type: dclDeploy
  #   steps:
  #     - IN: dcl-service1
  #     - IN: dclCluster
  #     - TASK: managed
      
  # - name: run-sample_python
  #   type: runCI
  #   steps:
  #     - IN: samplePython
  #     # - OUT: nginx-image
  #     - IN: triggerSamplePythonCI
  #     - TASK: managed
  
  - name: release1
    type: release
    steps:
      - IN: release2
      # - IN: manifest1
      - IN: triggerRelease1
      - TASK: managed
        # bump: major

  - name: release2
    type: release
    steps:
      - IN: version2
      - IN: manifest1
      - IN: triggerRelease2
      - TASK: managed

  # - name: release3
  #   type: release
  #   steps:
  #     - IN: version3
  #     - TASK: managed

  # - name: sh-sample-python
  #   type: runSh
  #   steps:
  #     IN: samplePython
  #     TASK: managed
  #       script: ls
