triggers:
  - name: trigger1
    type: trigger
    source:
      counter: 8
      
  - name: trigger2
    type: trigger
    source:
      counter: 8
      
  - name: triggerGKE
    type: trigger
    source:
      counter: 5
