triggers:
  - name: trigger1
    type: trigger
    pointer:
      counter: 9
      
  - name: trigger2
    type: trigger
    pointer:
      counter: 5
      
  - name: triggerGKE
    type: trigger
    pointer:
      counter: 10
  
  - name: triggerGKE2
    type: trigger
    pointer:
      counter: 24
  
  - name: triggerECS
    type: trigger
    pointer:
      counter: 9

  - name: triggerECS2
    type: trigger
    pointer:
      counter: 7
  
  - name: triggerRelease1
    type: trigger
    pointer:
      counter: 1
  
  - name: triggerSamplePythonCI
    type: trigger
    pointer:
      counter: 1
      
  - name: triggerTripub
    type: trigger
    pointer:
      counter: 1
