triggers:
  - name: triggerManifest1
    type: trigger
    pointer:
      counter: 34
      
  - name: triggerManifest2
    type: trigger
    pointer:
      counter: 17
      
  # - name: triggerGKE
  #   type: trigger
  #   pointer:
  #     counter: 29
  
  - name: triggerGKE2
    type: trigger
    pointer:
      counter: 50
  
  - name: triggerECS
    type: trigger
    pointer:
      counter: 2

  # - name: triggerECS2
  #   type: trigger
  #   pointer:
  #     counter: 7
  
  - name: triggerRelease1
    type: trigger
    pointer:
      counter: 12
  
  - name: triggerRelease2
    type: trigger
    pointer:
      counter: 1
  
  - name: triggerSamplePythonCI
    type: trigger
    pointer:
      counter: 1
      
  - name: triggerTripub
    type: trigger
    pointer:
      counter: 3
