jobs:
  - name: b-manifest1
    type: manifest
    steps:
      - GET: nginx-image
      - GET: trigger2
      # - GET: doesntExist
      # - GET: replicas1
      # - GET: dockerOptions1

  - name: b-manifest8
    type: manifest
    steps:
      # - GET: params2
      # - GET: b-manifest1
      - GET: replicas2
      - GET: b-manifest1
      - GET: trigger1

  - name: b-manifest9
    type: manifest
    steps:
      # - GET: params2
      - GET: replicas3

  - name: b-manifest17
    type: manifest
    steps:
      - GET: nginx-image

  - name: gke-cluster
    type: gkeDeploy
    steps:
      - GET: gkeCluster
      - GET: b-manifest1
      - GET: dockerOptions1
      - GET: triggerGKE

  # - name: my-ecs-service1
  #   type: ecsDeploy
  #   steps:
  #     - GET: my-manifest1
      # - GET: my-manifest2
      # - GET: release1
      # - GET: ecsCluster
      # - GET: replicas2
      #   applyTo: 
      #     - my-manifest1
      #     - my-manifest2
      # - GET: params1
        # applyTo:
        #   - not-an-image
      # - GET: dockerOptions2
        # applyTo:
        #   - not-an-image
      # - GET: kickstarter
      # - PUT: nginx-image
      
  # - name: ecs-service2
  #   type: ecsDeploy
  #   steps:
  #     - GET: ecs-service1
  #     - GET: my-manifest2
  #     - GET: ecsCluster
  #     - GET: replicas3
      # - GET: params3
      # - GET: dockerOptions3
      
  # - name: dcl-service1
  #   type: dclDeploy
  #   steps:
  #     - GET: manifest2
  #     - GET: dclCluster
      
  # - name: dcl-service2
  #   type: dclDeploy
  #   steps:
  #     - GET: dcl-service1
  #     - GET: dclCluster
      
  # - name: run-sample_python
  #   type: runCI
  #   steps:
  #     - GET: sample_python
  #     - PUT: nginx-image
  
  # - name: release1
  #   type: release
  #   options:
  #     action: minor
  #   steps:
  #     - GET: version3
  #     - GET: my-manifest2

  # - name: release3
  #   type: release
  #   options:
  #     action: minor
  #   steps:
  #     - GET: version3
