jobs:

  - name: runCLIJob
    type: runCLI
    steps:
#      - IN: ecrConfig
      - IN: awsConfig      
      - IN: sample_pipelines
#      - IN: kubernetesConfig
#      - IN: quayConfig    
#      - IN: dockerHubConfig
      - TASK:
        - script: echo $SAMPLE_PIPELINES_PATH
        - script: ls -la $SAMPLE_PIPELINES_PATH/gitRepo
        - script: echo "hello world"
#        - script: terraform --version
#        - script: eb init "my-application-name" -r "us-west-2" -p "Node.js"
#        - script: eb terminate --all --force "my-application-name"
#        - script: aws ecs list-clusters
#        - script: docker --version
#        - script: docker pull stephanielingwood/band-name-generator
#        - script: docker pull quay.io/stephanielingwood/busybox:version1
#        - script: docker pull 003199252576.dkr.ecr.us-east-1.amazonaws.com/php:5.5
#        - script: kubectl get namespaces


# ==================== manifests
  - name: manifest1
    type: manifest
    steps:
      - IN: nginx-image
      - IN: params1
      - IN: replicas0      
      - TASK: managed
#     on_start:
#       - NOTIFY: slackNotification
#     on_success:
#       - NOTIFY: slackNotification
#     on_failure:
#       - NOTIFY: slackNotification


  - name: manifest2
    type: manifest
    steps:
      - IN: busybox-image
      - IN: params1
      - IN: replicas2      
      - TASK: managed      

  - name: manifest3
    type: manifest
    steps:
#      - IN: params1
#      - IN: replicas0
      - IN: scratch-image
      - TASK: managed      
      
#  - name: manifestIntoManifest
#    type: manifest
#    steps:
#      - IN: manifest1
#      - IN: manifest2
#      - IN: replicas2
#     - TASK: managed      
   
#  - name: manifestQuayPrivate
#    type: manifest
#    steps:
#      - IN: sample-node-quay-private
#      - TASK: managed  

#  - name: manifestGcrPrivate
#    type: manifest
#    steps:
#      - IN: busybox-gcr-private-image
#      - TASK: managed


# ==================== deploys
#  - name: gkeDeploy
#    type: deploy
#    steps:
#      - IN: manifest1
#      - IN: gkeCluster
#        deployMethod: upgrade

  - name: ecsDeploy
    type: deploy
    steps:
      - IN: manifest1
      - IN: manifest2
#      - IN: manifest3
      - IN: ecsCluster
      - TASK: managed
        deployMethod: upgrade      
        
#  - name: tripubDeploy
#    type: deploy
#    steps:
#      - IN: manifest1
#      - IN: tritonCluster
#      - TASK: managed
#        deployMethod: replace
      
#  - name: dclDeploy
#    type: deploy
#    steps:
#      - IN: manifest1
#      - IN: dclCluster
#      - TASK: managed
#        deployMethod: upgrade

#  - name: ddcDeploy
#    type: deploy
#    steps:
#      - IN: manifest1
#      - IN: replicas0
#      - IN: ddcCluster
#      - TASK: managed
#        deployMethod: upgrade

#  - name: ecsDeployWithLB
#    type: deploy
#    steps:
#      - IN: manifest2
#      - IN: stephLB
#        applyTo:
#         - manifest: manifest4
#           image: scratch-image
#           port: 3001
#      - IN: ecsCluster
#      - TASK: managed
#        deployMethod: upgrade   


# ==================== provisions
  - name: gkeProvisionService
    type: provision
    steps:
      - IN: params1
      - IN: gkeProvisionLoadBalancer
      - IN: gkeProvisionLoadBalancerToo
      - TASK: managed


# ==================== release
  - name: release1
    type: release
    steps:
#      - IN: ecsDeploy
      - IN: version1
      - IN: manifest3
      - IN: triggerRelease1
      - TASK: managed
      #   bump: major


# ==================== runSh
  - name: runSh
    type: runSh
    steps:
      - IN: nginx-image
#      - IN: params1
#      - IN: paramsSecure
#      - IN: fakeGKEIntegration
      - IN: samplePython
#      - IN: awsIntegration
      - TASK:
        - script: "pwd"
     #   - script: "ls"
        - script: printenv
       # - script: cd doesntexist
#    on_success: 
#      - script: echo "on success------------------"
#      - script: cd doesntexist
#    on_failure: 
#      - script: echo "on failure------------------"
#      - script: cd doesntexist
#    always:
#      - script: echo "always"

      # - OUT: nginx-image

  # - name: sh-sample-python
  #   type: runSh
  #   steps:
  #     IN: samplePython
  #     TASK: managed
  #       script: ls
  
