triggers:
  - name: triggerb1
    type: trigger
    pointer:
      counter: 9
      
  - name: triggerb8
    type: trigger
    pointer:
      counter: 9
      
  - name: triggerGKE
    type: trigger
    pointer:
      counter: 47
  
  - name: triggerECS
    type: trigger
    pointer:
      counter: 22
  
  - name: triggerRelease1
    type: trigger
    pointer:
      counter: 5
  
  - name: triggerSamplePythonCI
    type: trigger
    pointer:
      counter: 7
      
  - name: triggerTripub
    type: trigger
    pointer:
      counter: 5
