triggers:
  - name: trigger1
    type: trigger
    pointer:
      counter: 1
      
  - name: trigger2
    type: trigger
    pointer:
      counter: 1
      
  - name: triggerGKE
    type: trigger
    pointer:
      counter: 1
  
  - name: triggerECS
    type: trigger
    pointer:
      counter: 1
  
  - name: triggerRelease1
    type: trigger
    pointer:
      counter: 1
  
  - name: triggerSamplePythonCI
    type: trigger
    pointer:
      counter: 1
      
  - name: triggerTripub
    type: trigger
    pointer:
      counter: 1
