triggers:
  - name: trigger1
    type: trigger
    pointer:
      counter: 8
      
  - name: trigger2
    type: trigger
    pointer:
      counter: 8
      
  - name: triggerGKE
    type: trigger
    pointer:
      counter: 22
  
  - name: triggerECS
    type: trigger
    pointer:
      counter: 9
  
  - name: triggerRelease1
    type: trigger
    pointer:
      counter: 5
  
  - name: triggerSamplePythonCI
    type: trigger
    pointer:
      counter: 7
